// Account database for Egg Roller Idle.
// Auto-updated by server.js on register and save.
const users = {
  "user14109": {
    "password": "test1234",
    "coins": 0,
    "gems": 0,
    "rolls": 0,
    "createdAt": 1780123569780
  },
  "Danny": {
    "password": "Danny@201424",
    "coins": 427605741,
    "gems": 35794,
    "rolls": 30215686,
    "createdAt": 1780123726260,
    "save": {
      "version": 1,
      "username": "Danny",
      "coins": 427605741,
      "gems": 35794,
      "eggs": {
        "Common": 11322766,
        "Uncommon": 17219487,
        "Rare": 1464971,
        "Epic": 145570,
        "Legendary": 14362,
        "Fabled": 2997,
        "Mythic": 1437,
        "Divine": 146,
        "Celestial": 13,
        "Void": 3,
        "Astral": 1,
        "Ethereal": 0,
        "Omnipotent": 0,
        "Infinity": 0,
        "Absolute": 0
      },
      "eggCollection": {
        "common_barn": 1887841,
        "common_pebble": 1888686,
        "common_clover": 1887341,
        "common_dusk": 1886957,
        "common_hay": 1884918,
        "common_mist": 1887023,
        "uncommon_moss": 2870768,
        "uncommon_fern": 2869824,
        "uncommon_bamboo": 2869283,
        "uncommon_creek": 2871455,
        "uncommon_thistle": 2870729,
        "uncommon_vine": 2867428,
        "rare_sapphire": 243872,
        "rare_cobalt": 244382,
        "rare_azure": 244241,
        "rare_indigo": 243646,
        "rare_lapis": 244246,
        "rare_teal": 244584,
        "epic_arcane": 24309,
        "epic_rune": 24109,
        "epic_hex": 24218,
        "epic_spell": 24404,
        "epic_crystal": 24353,
        "epic_mystic": 24177,
        "legendary_golden": 2345,
        "legendary_solar": 2501,
        "legendary_midas": 2412,
        "legendary_aurora": 2344,
        "legendary_crown": 2320,
        "legendary_dawn": 2440,
        "fabled_suncrest": 553,
        "fabled_halcyon": 513,
        "fabled_radiant": 492,
        "fabled_gilded": 480,
        "fabled_solstice": 475,
        "fabled_zenith": 484,
        "mythic_crimson": 248,
        "mythic_ember": 239,
        "mythic_inferno": 252,
        "mythic_bloodstone": 229,
        "mythic_magma": 244,
        "mythic_scorch": 225,
        "divine_seraph": 25,
        "divine_halo": 21,
        "divine_grace": 28,
        "divine_sanctum": 21,
        "divine_choir": 23,
        "divine_relic": 28,
        "celestial_nebula": 4,
        "celestial_comet": 2,
        "celestial_orbit": 1,
        "celestial_pulsar": 3,
        "celestial_lunar": 1,
        "celestial_stellar": 2,
        "void_abyss": 0,
        "void_null": 1,
        "void_oblivion": 1,
        "void_eclipse": 1,
        "void_hollow": 0,
        "void_rift": 0,
        "astral_cosmos": 0,
        "astral_quasar": 0,
        "astral_galaxy": 0,
        "astral_supernova": 1,
        "astral_neutron": 0,
        "astral_parallax": 0,
        "ethereal_phantom": 0,
        "ethereal_wisp": 0,
        "ethereal_mirage": 0,
        "ethereal_specter": 0,
        "ethereal_veil": 0,
        "ethereal_echo": 0,
        "omnipotent_titan": 0,
        "omnipotent_sovereign": 0,
        "omnipotent_dominus": 0,
        "omnipotent_apex": 0,
        "omnipotent_colossus": 0,
        "omnipotent_throne": 0,
        "infinity_eternal": 0,
        "infinity_boundless": 0,
        "infinity_limitless": 0,
        "infinity_evermore": 0,
        "infinity_loop": 0,
        "infinity_horizon": 0,
        "absolute_zenith": 0,
        "absolute_omega": 0,
        "absolute_primordial": 0,
        "absolute_core": 0,
        "absolute_nadir": 0,
        "absolute_singularity": 0,
        "fusion_prism": 0,
        "fusion_chimera": 0,
        "fusion_nova": 0,
        "fusion_seraphic": 0,
        "fusion_eclipse": 0,
        "fusion_abyssal": 0,
        "fusion_astral": 0,
        "fusion_omega": 0,
        "fusion_infinite": 0,
        "fusion_absolute": 0,
        "fusion_supernova": 0,
        "fusion_singularity": 0,
        "fusion_paragon": 0,
        "fusion_transcendent": 0,
        "fusion_omnistar": 0,
        "fusion_cascade": 0,
        "fusion_radiant": 0,
        "fusion_phantom": 0
      },
      "shinyCollection": {
        "common_barn": 85632,
        "common_pebble": 85455,
        "common_clover": 85154,
        "common_dusk": 85657,
        "common_hay": 84997,
        "common_mist": 85570,
        "uncommon_moss": 129667,
        "uncommon_fern": 129803,
        "uncommon_bamboo": 130593,
        "uncommon_creek": 129990,
        "uncommon_thistle": 129877,
        "uncommon_vine": 129745,
        "rare_sapphire": 11345,
        "rare_cobalt": 11246,
        "rare_azure": 11333,
        "rare_indigo": 11313,
        "rare_lapis": 11384,
        "rare_teal": 11344,
        "epic_arcane": 1180,
        "epic_rune": 1132,
        "epic_hex": 1114,
        "epic_spell": 1134,
        "epic_crystal": 1069,
        "epic_mystic": 1198,
        "legendary_golden": 123,
        "legendary_solar": 121,
        "legendary_midas": 103,
        "legendary_aurora": 112,
        "legendary_crown": 109,
        "legendary_dawn": 113,
        "fabled_suncrest": 23,
        "fabled_halcyon": 21,
        "fabled_radiant": 23,
        "fabled_gilded": 28,
        "fabled_solstice": 24,
        "fabled_zenith": 21,
        "mythic_crimson": 8,
        "mythic_ember": 18,
        "mythic_inferno": 15,
        "mythic_bloodstone": 10,
        "mythic_magma": 10,
        "mythic_scorch": 10,
        "divine_seraph": 0,
        "divine_halo": 1,
        "divine_grace": 2,
        "divine_sanctum": 1,
        "divine_choir": 1,
        "divine_relic": 1,
        "celestial_nebula": 0,
        "celestial_comet": 0,
        "celestial_orbit": 0,
        "celestial_pulsar": 0,
        "celestial_lunar": 0,
        "celestial_stellar": 0,
        "void_abyss": 0,
        "void_null": 0,
        "void_oblivion": 0,
        "void_eclipse": 0,
        "void_hollow": 0,
        "void_rift": 0,
        "astral_cosmos": 0,
        "astral_quasar": 0,
        "astral_galaxy": 0,
        "astral_supernova": 0,
        "astral_neutron": 0,
        "astral_parallax": 0,
        "ethereal_phantom": 0,
        "ethereal_wisp": 0,
        "ethereal_mirage": 0,
        "ethereal_specter": 0,
        "ethereal_veil": 0,
        "ethereal_echo": 0,
        "omnipotent_titan": 0,
        "omnipotent_sovereign": 0,
        "omnipotent_dominus": 0,
        "omnipotent_apex": 0,
        "omnipotent_colossus": 0,
        "omnipotent_throne": 0,
        "infinity_eternal": 0,
        "infinity_boundless": 0,
        "infinity_limitless": 0,
        "infinity_evermore": 0,
        "infinity_loop": 0,
        "infinity_horizon": 0,
        "absolute_zenith": 0,
        "absolute_omega": 0,
        "absolute_primordial": 0,
        "absolute_core": 0,
        "absolute_nadir": 0,
        "absolute_singularity": 0
      },
      "lastEggId": "rare_lapis",
      "discoveredEggs": {
        "uncommon_vine": true,
        "uncommon_bamboo": true,
        "common_dusk": true,
        "common_clover": true,
        "uncommon_thistle": true,
        "common_hay": true,
        "uncommon_creek": true,
        "uncommon_moss": true,
        "common_mist": true,
        "common_pebble": true,
        "uncommon_fern": true,
        "rare_cobalt": true,
        "common_barn": true,
        "rare_indigo": true,
        "rare_teal": true,
        "rare_azure": true,
        "legendary_golden": true,
        "rare_lapis": true,
        "epic_mystic": true,
        "rare_sapphire": true,
        "mythic_crimson": true,
        "epic_spell": true,
        "epic_arcane": true,
        "epic_hex": true,
        "legendary_dawn": true,
        "epic_crystal": true,
        "legendary_crown": true,
        "legendary_solar": true,
        "epic_rune": true,
        "fabled_suncrest": true,
        "fabled_halcyon": true,
        "legendary_aurora": true,
        "legendary_midas": true,
        "fabled_radiant": true,
        "fabled_gilded": true,
        "mythic_magma": true,
        "fabled_solstice": true,
        "mythic_scorch": true,
        "fabled_zenith": true,
        "mythic_ember": true,
        "mythic_bloodstone": true,
        "mythic_inferno": true,
        "divine_halo": true,
        "divine_seraph": true,
        "divine_grace": true,
        "divine_choir": true,
        "celestial_orbit": true,
        "divine_sanctum": true,
        "void_null": true,
        "celestial_pulsar": true,
        "celestial_nebula": true,
        "divine_relic": true,
        "void_eclipse": true,
        "celestial_stellar": true,
        "celestial_lunar": true,
        "void_oblivion": true,
        "celestial_comet": true,
        "astral_supernova": true
      },
      "discoveredShinyEggs": {
        "common_hay": true,
        "common_mist": true,
        "uncommon_thistle": true,
        "uncommon_fern": true,
        "uncommon_creek": true,
        "common_barn": true,
        "uncommon_moss": true,
        "uncommon_vine": true,
        "common_dusk": true,
        "common_pebble": true,
        "uncommon_bamboo": true,
        "common_clover": true,
        "rare_lapis": true,
        "rare_azure": true,
        "rare_cobalt": true,
        "rare_sapphire": true,
        "rare_teal": true,
        "rare_indigo": true,
        "epic_crystal": true,
        "epic_rune": true,
        "epic_arcane": true,
        "epic_mystic": true,
        "epic_spell": true,
        "legendary_dawn": true,
        "epic_hex": true,
        "legendary_solar": true,
        "legendary_golden": true,
        "fabled_suncrest": true,
        "legendary_midas": true,
        "mythic_scorch": true,
        "fabled_zenith": true,
        "fabled_gilded": true,
        "fabled_solstice": true,
        "legendary_crown": true,
        "legendary_aurora": true,
        "mythic_crimson": true,
        "mythic_magma": true,
        "fabled_halcyon": true,
        "mythic_inferno": true,
        "divine_sanctum": true,
        "mythic_ember": true,
        "fabled_radiant": true,
        "mythic_bloodstone": true,
        "divine_grace": true,
        "divine_halo": true,
        "divine_choir": true,
        "divine_relic": true
      },
      "showcase": [
        {
          "eggId": "divine_sanctum",
          "shiny": true
        },
        {
          "eggId": "void_eclipse",
          "shiny": false
        },
        {
          "eggId": "void_oblivion",
          "shiny": false
        }
      ],
      "titles": [
        "newRoller",
        "shinyCollector",
        "diceGrinder",
        "codexHunter",
        "voidWalker"
      ],
      "activeTitle": "voidWalker",
      "upgrades": {
        "auto1": 12,
        "auto2": 30,
        "auto3": 25,
        "auto4": 24,
        "auto5": 20,
        "luck": 49,
        "coinMult": 41,
        "fastRoll": 33,
        "eggValue": 19
      },
      "gemUpgrades": {
        "gemLuck": 0,
        "gemCoins": 0,
        "gemAuto": 0,
        "gemValue": 0,
        "gemPrestige": 0
      },
      "totalRolls": 30215686,
      "rollsSincePrestige": 30215686,
      "totalCoinsEarned": 20883129103,
      "totalGemsEarned": 115719,
      "rarestEgg": "Astral",
      "eventLog": [
        {
          "type": "shiny",
          "message": "Shiny found: Bamboo Egg [Uncommon]!",
          "at": 1781272402186
        },
        {
          "type": "shiny",
          "message": "Shiny found: Creek Egg [Uncommon]!",
          "at": 1781272402087
        },
        {
          "type": "shiny",
          "message": "Shiny found: Thistle Egg [Uncommon]!",
          "at": 1781272401992
        },
        {
          "type": "shiny",
          "message": "Shiny found: Moss Egg [Uncommon]!",
          "at": 1781272401886
        },
        {
          "type": "shiny",
          "message": "Shiny found: Moss Egg [Uncommon]!",
          "at": 1781272401787
        },
        {
          "type": "shiny",
          "message": "Shiny found: Moss Egg [Uncommon]!",
          "at": 1781272401686
        },
        {
          "type": "shiny",
          "message": "Shiny found: Vine Egg [Uncommon]!",
          "at": 1781272401586
        },
        {
          "type": "shiny",
          "message": "Shiny found: Moss Egg [Uncommon]!",
          "at": 1781272401487
        },
        {
          "type": "shiny",
          "message": "Shiny found: Vine Egg [Uncommon]!",
          "at": 1781272401386
        },
        {
          "type": "shiny",
          "message": "Shiny found: Bamboo Egg [Uncommon]!",
          "at": 1781272401286
        },
        {
          "type": "shiny",
          "message": "Shiny found: Vine Egg [Uncommon]!",
          "at": 1781272401186
        },
        {
          "type": "shiny",
          "message": "Shiny found: Fern Egg [Uncommon]!",
          "at": 1781272401086
        },
        {
          "type": "shiny",
          "message": "Shiny found: Thistle Egg [Uncommon]!",
          "at": 1781272400986
        },
        {
          "type": "shiny",
          "message": "Shiny found: Fern Egg [Uncommon]!",
          "at": 1781272400886
        },
        {
          "type": "shiny",
          "message": "Shiny found: Creek Egg [Uncommon]!",
          "at": 1781272400786
        },
        {
          "type": "shiny",
          "message": "Shiny found: Vine Egg [Uncommon]!",
          "at": 1781272400687
        },
        {
          "type": "shiny",
          "message": "Shiny found: Moss Egg [Uncommon]!",
          "at": 1781272400586
        },
        {
          "type": "shiny",
          "message": "Shiny found: Vine Egg [Uncommon]!",
          "at": 1781272400487
        },
        {
          "type": "shiny",
          "message": "Shiny found: Bamboo Egg [Uncommon]!",
          "at": 1781272400388
        },
        {
          "type": "shiny",
          "message": "Shiny found: Fern Egg [Uncommon]!",
          "at": 1781272400286
        }
      ],
      "completedSets": {
        "Uncommon": true,
        "Common": true,
        "Rare": true,
        "Epic": true,
        "Legendary": true,
        "Fabled": true,
        "Mythic": true,
        "Divine": true,
        "Celestial": true
      },
      "activeSetBonuses": {
        "setUncommon": true,
        "setCommon": true,
        "setRare": true,
        "setEpic": true,
        "setLegendary": true,
        "setFabled": true,
        "setMythic": true,
        "setDivine": true,
        "setCelestial": true
      },
      "hatchedCompanions": {},
      "activeCompanionId": null,
      "fusionCraftCount": 0,
      "ascensionLevel": 0,
      "ascensionPoints": 0,
      "ascensionUpgrades": {
        "ascLuck": 0,
        "ascCoins": 0,
        "ascRps": 0
      },
      "dicePurchases": 0,
      "currentEventId": "eventLuck",
      "currentEventGeneratedAt": 1781271885944,
      "currentEventData": {
        "id": "eventLuck",
        "label": "Double Luck Weekend",
        "luck": 0.5
      },
      "currentEventFetchedAt": 1781271885944,
      "manualStreak": 0,
      "lastManualRollAt": 1781177224279,
      "luckyRollAvailableAt": 1781177254279,
      "lastSessionAt": 1781272402232,
      "playtimeMs": 37055547.900000036,
      "prestigeLevel": 0,
      "prestigePoints": 0,
      "achievementsUnlocked": {
        "coins_1m": 1781176763279,
        "rare_egg": 1781176811885,
        "first_shiny": 1781176811996,
        "roll_100": 1781176812495,
        "legendary_egg": 1781176812785,
        "epic_egg": 1781176812895,
        "shiny_10": 1781176812895,
        "jackpot_1": 1781176813892,
        "roll_1k": 1781176814686,
        "roll_10k": 1781176827486,
        "gems_500": 1781177226898,
        "shiny_divine": 1781224402173,
        "void_egg": 1781224900973,
        "astral_egg": 1781272092690
      },
      "settings": {
        "darkMode": true,
        "soundEnabled": true,
        "language": "zh",
        "activeTheme": "neon",
        "unlockedThemes": [
          "classic",
          "meadow",
          "sunset",
          "ocean",
          "neon",
          "sakura"
        ],
        "filters": {
          "collectionSearch": "",
          "codexSearch": "",
          "collectionRarity": "all",
          "collectionOwned": "all",
          "codexRarity": "all",
          "codexOwned": "all",
          "codexShinyOnly": false,
          "shopSearch": "",
          "gemShopSearch": ""
        }
      },
      "daily": {
        "lastClaimAt": 1781252857386
      },
      "stats": {
        "rollsSinceLastEgg": 0,
        "rollsSinceLastRarePlus": 0,
        "jackpotsHit": 30204
      },
      "duelBuffExpiresAt": 0,
      "lastSavedAt": 1781272402232,
      "prestigeMilestonesClaimed": [],
      "prestigeMilestoneLuck": 0,
      "weeklyChallenges": {
        "weekId": 2945,
        "tasks": {
          "rolls_500": {
            "progress": 500,
            "claimed": true
          },
          "fusion_3": {
            "progress": 0,
            "claimed": false
          },
          "hatch_1": {
            "progress": 0,
            "claimed": false
          },
          "discover_1": {
            "progress": 1,
            "claimed": false
          },
          "streak_10": {
            "progress": 0,
            "claimed": false
          }
        }
      },
      "guildId": null,
      "guildRole": null,
      "seasonRolls": 6253100
    }
  },
  "Enter_username": {
    "password": "Enter password",
    "coins": 5221780362,
    "gems": 3362,
    "rolls": 50165750,
    "createdAt": 1781176022969,
    "save": {
      "version": 1,
      "username": "Enter_username",
      "coins": 5221780362,
      "gems": 3362,
      "eggs": {
        "Common": 22715012,
        "Uncommon": 22691047,
        "Rare": 2054956,
        "Epic": 204534,
        "Legendary": 20424,
        "Fabled": 4107,
        "Mythic": 2032,
        "Divine": 198,
        "Celestial": 17,
        "Void": 2,
        "Astral": 0,
        "Ethereal": 0,
        "Omnipotent": 0,
        "Infinity": 0,
        "Absolute": 0
      },
      "eggCollection": {
        "common_barn": 3782910,
        "common_pebble": 3787392,
        "common_clover": 3784685,
        "common_dusk": 3787041,
        "common_hay": 3789026,
        "common_mist": 3783958,
        "uncommon_moss": 3782941,
        "uncommon_fern": 3781153,
        "uncommon_bamboo": 3781864,
        "uncommon_creek": 3781095,
        "uncommon_thistle": 3779920,
        "uncommon_vine": 3784074,
        "rare_sapphire": 341725,
        "rare_cobalt": 342012,
        "rare_azure": 342784,
        "rare_indigo": 342043,
        "rare_lapis": 344066,
        "rare_teal": 342326,
        "epic_arcane": 34319,
        "epic_rune": 34152,
        "epic_hex": 34367,
        "epic_spell": 33828,
        "epic_crystal": 34157,
        "epic_mystic": 33711,
        "legendary_golden": 3409,
        "legendary_solar": 3439,
        "legendary_midas": 3448,
        "legendary_aurora": 3397,
        "legendary_crown": 3348,
        "legendary_dawn": 3383,
        "fabled_suncrest": 677,
        "fabled_halcyon": 690,
        "fabled_radiant": 664,
        "fabled_gilded": 691,
        "fabled_solstice": 703,
        "fabled_zenith": 682,
        "mythic_crimson": 345,
        "mythic_ember": 368,
        "mythic_inferno": 324,
        "mythic_bloodstone": 317,
        "mythic_magma": 352,
        "mythic_scorch": 326,
        "divine_seraph": 28,
        "divine_halo": 43,
        "divine_grace": 36,
        "divine_sanctum": 29,
        "divine_choir": 39,
        "divine_relic": 23,
        "celestial_nebula": 2,
        "celestial_comet": 5,
        "celestial_orbit": 0,
        "celestial_pulsar": 1,
        "celestial_lunar": 4,
        "celestial_stellar": 5,
        "void_abyss": 1,
        "void_null": 0,
        "void_oblivion": 0,
        "void_eclipse": 1,
        "void_hollow": 0,
        "void_rift": 0,
        "astral_cosmos": 0,
        "astral_quasar": 0,
        "astral_galaxy": 0,
        "astral_supernova": 0,
        "astral_neutron": 0,
        "astral_parallax": 0,
        "ethereal_phantom": 0,
        "ethereal_wisp": 0,
        "ethereal_mirage": 0,
        "ethereal_specter": 0,
        "ethereal_veil": 0,
        "ethereal_echo": 0,
        "omnipotent_titan": 0,
        "omnipotent_sovereign": 0,
        "omnipotent_dominus": 0,
        "omnipotent_apex": 0,
        "omnipotent_colossus": 0,
        "omnipotent_throne": 0,
        "infinity_eternal": 0,
        "infinity_boundless": 0,
        "infinity_limitless": 0,
        "infinity_evermore": 0,
        "infinity_loop": 0,
        "infinity_horizon": 0,
        "absolute_zenith": 0,
        "absolute_omega": 0,
        "absolute_primordial": 0,
        "absolute_core": 0,
        "absolute_nadir": 0,
        "absolute_singularity": 0,
        "fusion_prism": 0,
        "fusion_chimera": 0,
        "fusion_nova": 0,
        "fusion_seraphic": 0,
        "fusion_eclipse": 0,
        "fusion_abyssal": 0,
        "fusion_astral": 0,
        "fusion_omega": 0,
        "fusion_infinite": 0,
        "fusion_absolute": 0,
        "fusion_supernova": 0,
        "fusion_singularity": 0,
        "fusion_paragon": 0,
        "fusion_transcendent": 0,
        "fusion_omnistar": 0,
        "fusion_cascade": 0,
        "fusion_radiant": 0,
        "fusion_phantom": 0
      },
      "shinyCollection": {
        "common_barn": 158745,
        "common_pebble": 159743,
        "common_clover": 159874,
        "common_dusk": 160044,
        "common_hay": 159545,
        "common_mist": 159859,
        "uncommon_moss": 173928,
        "uncommon_fern": 173491,
        "uncommon_bamboo": 173770,
        "uncommon_creek": 174012,
        "uncommon_thistle": 173484,
        "uncommon_vine": 173586,
        "rare_sapphire": 15679,
        "rare_cobalt": 15331,
        "rare_azure": 15404,
        "rare_indigo": 15433,
        "rare_lapis": 15500,
        "rare_teal": 15540,
        "epic_arcane": 1439,
        "epic_rune": 1507,
        "epic_hex": 1509,
        "epic_spell": 1437,
        "epic_crystal": 1566,
        "epic_mystic": 1583,
        "legendary_golden": 148,
        "legendary_solar": 135,
        "legendary_midas": 123,
        "legendary_aurora": 148,
        "legendary_crown": 146,
        "legendary_dawn": 147,
        "fabled_suncrest": 28,
        "fabled_halcyon": 30,
        "fabled_radiant": 21,
        "fabled_gilded": 25,
        "fabled_solstice": 20,
        "fabled_zenith": 18,
        "mythic_crimson": 14,
        "mythic_ember": 17,
        "mythic_inferno": 15,
        "mythic_bloodstone": 16,
        "mythic_magma": 12,
        "mythic_scorch": 17,
        "divine_seraph": 1,
        "divine_halo": 2,
        "divine_grace": 2,
        "divine_sanctum": 0,
        "divine_choir": 0,
        "divine_relic": 1,
        "celestial_nebula": 0,
        "celestial_comet": 0,
        "celestial_orbit": 0,
        "celestial_pulsar": 0,
        "celestial_lunar": 0,
        "celestial_stellar": 0,
        "void_abyss": 0,
        "void_null": 0,
        "void_oblivion": 0,
        "void_eclipse": 0,
        "void_hollow": 0,
        "void_rift": 0,
        "astral_cosmos": 0,
        "astral_quasar": 0,
        "astral_galaxy": 0,
        "astral_supernova": 0,
        "astral_neutron": 0,
        "astral_parallax": 0,
        "ethereal_phantom": 0,
        "ethereal_wisp": 0,
        "ethereal_mirage": 0,
        "ethereal_specter": 0,
        "ethereal_veil": 0,
        "ethereal_echo": 0,
        "omnipotent_titan": 0,
        "omnipotent_sovereign": 0,
        "omnipotent_dominus": 0,
        "omnipotent_apex": 0,
        "omnipotent_colossus": 0,
        "omnipotent_throne": 0,
        "infinity_eternal": 0,
        "infinity_boundless": 0,
        "infinity_limitless": 0,
        "infinity_evermore": 0,
        "infinity_loop": 0,
        "infinity_horizon": 0,
        "absolute_zenith": 0,
        "absolute_omega": 0,
        "absolute_primordial": 0,
        "absolute_core": 0,
        "absolute_nadir": 0,
        "absolute_singularity": 0
      },
      "lastEggId": "common_pebble",
      "discoveredEggs": {
        "common_barn": true,
        "common_dusk": true,
        "rare_teal": true,
        "common_clover": true,
        "rare_azure": true,
        "common_mist": true,
        "uncommon_thistle": true,
        "common_pebble": true,
        "uncommon_vine": true,
        "common_hay": true,
        "uncommon_creek": true,
        "uncommon_fern": true,
        "uncommon_moss": true,
        "rare_cobalt": true,
        "rare_sapphire": true,
        "uncommon_bamboo": true,
        "rare_lapis": true,
        "epic_arcane": true,
        "epic_spell": true,
        "epic_rune": true,
        "epic_hex": true,
        "rare_indigo": true,
        "fabled_zenith": true,
        "fabled_suncrest": true,
        "legendary_golden": true,
        "epic_crystal": true,
        "epic_mystic": true,
        "fabled_gilded": true,
        "legendary_crown": true,
        "fabled_radiant": true,
        "legendary_midas": true,
        "legendary_dawn": true,
        "mythic_magma": true,
        "legendary_aurora": true,
        "mythic_bloodstone": true,
        "legendary_solar": true,
        "fabled_solstice": true,
        "mythic_ember": true,
        "mythic_scorch": true,
        "fabled_halcyon": true,
        "mythic_inferno": true,
        "mythic_crimson": true,
        "divine_seraph": true,
        "divine_grace": true,
        "divine_relic": true,
        "celestial_nebula": true,
        "fusion_prism": true,
        "divine_halo": true,
        "divine_choir": true,
        "celestial_lunar": true,
        "divine_sanctum": true,
        "celestial_pulsar": true,
        "celestial_stellar": true,
        "celestial_comet": true,
        "void_abyss": true,
        "void_eclipse": true
      },
      "discoveredShinyEggs": {
        "common_clover": true,
        "common_hay": true,
        "common_barn": true,
        "uncommon_fern": true,
        "uncommon_creek": true,
        "uncommon_moss": true,
        "common_pebble": true,
        "uncommon_bamboo": true,
        "common_dusk": true,
        "uncommon_vine": true,
        "rare_teal": true,
        "common_mist": true,
        "rare_lapis": true,
        "uncommon_thistle": true,
        "rare_sapphire": true,
        "rare_cobalt": true,
        "epic_crystal": true,
        "rare_indigo": true,
        "rare_azure": true,
        "epic_spell": true,
        "epic_hex": true,
        "epic_rune": true,
        "epic_arcane": true,
        "epic_mystic": true,
        "fabled_solstice": true,
        "mythic_bloodstone": true,
        "fabled_halcyon": true,
        "legendary_aurora": true,
        "legendary_dawn": true,
        "fabled_radiant": true,
        "divine_grace": true,
        "legendary_crown": true,
        "legendary_midas": true,
        "legendary_golden": true,
        "legendary_solar": true,
        "mythic_ember": true,
        "mythic_scorch": true,
        "mythic_inferno": true,
        "fabled_suncrest": true,
        "mythic_crimson": true,
        "fabled_zenith": true,
        "fabled_gilded": true,
        "mythic_magma": true,
        "divine_halo": true,
        "divine_relic": true,
        "divine_seraph": true
      },
      "showcase": [
        {
          "eggId": "celestial_nebula",
          "shiny": false
        },
        {
          "eggId": "divine_seraph",
          "shiny": false
        },
        {
          "eggId": "divine_grace",
          "shiny": false
        }
      ],
      "titles": [
        "newRoller",
        "shinyCollector",
        "diceGrinder",
        "codexHunter",
        "voidWalker"
      ],
      "activeTitle": "voidWalker",
      "upgrades": {
        "auto1": 30,
        "auto2": 22,
        "auto3": 14,
        "auto4": 9,
        "auto5": 4,
        "luck": 21,
        "coinMult": 21,
        "fastRoll": 22,
        "eggValue": 17
      },
      "gemUpgrades": {
        "gemLuck": 12,
        "gemCoins": 15,
        "gemAuto": 13,
        "gemValue": 4,
        "gemPrestige": 0
      },
      "totalRolls": 50165750,
      "rollsSincePrestige": 47699090,
      "totalCoinsEarned": 5556523715,
      "totalGemsEarned": 3814037,
      "rarestEgg": "Void",
      "eventLog": [
        {
          "type": "shiny",
          "message": "Shiny found: Thistle Egg [Uncommon]!",
          "at": 1781307242182
        },
        {
          "type": "shiny",
          "message": "Shiny found: Bamboo Egg [Uncommon]!",
          "at": 1781307242073
        },
        {
          "type": "shiny",
          "message": "Shiny found: Fern Egg [Uncommon]!",
          "at": 1781307241973
        },
        {
          "type": "shiny",
          "message": "Shiny found: Pebble Egg [Common]!",
          "at": 1781307241873
        },
        {
          "type": "shiny",
          "message": "Shiny found: Clover Egg [Common]!",
          "at": 1781307241775
        },
        {
          "type": "shiny",
          "message": "Shiny found: Dusk Egg [Common]!",
          "at": 1781307241674
        },
        {
          "type": "shiny",
          "message": "Shiny found: Barn Egg [Common]!",
          "at": 1781307241573
        },
        {
          "type": "shiny",
          "message": "Shiny found: Mist Egg [Common]!",
          "at": 1781307241474
        },
        {
          "type": "shiny",
          "message": "Shiny found: Barn Egg [Common]!",
          "at": 1781307241374
        },
        {
          "type": "shiny",
          "message": "Shiny found: Barn Egg [Common]!",
          "at": 1781307241273
        },
        {
          "type": "shiny",
          "message": "Shiny found: Mist Egg [Common]!",
          "at": 1781307241177
        },
        {
          "type": "shiny",
          "message": "Shiny found: Barn Egg [Common]!",
          "at": 1781307241073
        },
        {
          "type": "shiny",
          "message": "Shiny found: Pebble Egg [Common]!",
          "at": 1781307240973
        },
        {
          "type": "shiny",
          "message": "Shiny found: Fern Egg [Uncommon]!",
          "at": 1781307240874
        },
        {
          "type": "shiny",
          "message": "Shiny found: Mist Egg [Common]!",
          "at": 1781307240773
        },
        {
          "type": "shiny",
          "message": "Shiny found: Moss Egg [Uncommon]!",
          "at": 1781307240673
        },
        {
          "type": "shiny",
          "message": "Shiny found: Barn Egg [Common]!",
          "at": 1781307240573
        },
        {
          "type": "shiny",
          "message": "Shiny found: Hay Egg [Common]!",
          "at": 1781307240474
        },
        {
          "type": "shiny",
          "message": "Shiny found: Hay Egg [Common]!",
          "at": 1781307240373
        },
        {
          "type": "shiny",
          "message": "Shiny found: Mist Egg [Common]!",
          "at": 1781307240273
        }
      ],
      "completedSets": {
        "Common": true,
        "Uncommon": true,
        "Rare": true,
        "Epic": true,
        "Legendary": true,
        "Fabled": true,
        "Mythic": true,
        "Divine": true
      },
      "activeSetBonuses": {
        "setCommon": true,
        "setUncommon": true,
        "setRare": true,
        "setEpic": true,
        "setLegendary": true,
        "setFabled": true,
        "setMythic": true,
        "setDivine": true
      },
      "hatchedCompanions": {},
      "activeCompanionId": null,
      "fusionCraftCount": 1,
      "ascensionLevel": 6,
      "ascensionPoints": 0,
      "ascensionUpgrades": {
        "ascLuck": 0,
        "ascCoins": 0,
        "ascRps": 1
      },
      "dicePurchases": 2,
      "secondDieOwned": true,
      "secondDiePurchases": 0,
      "secondDieUpgrades": {
        "die2Auto1": 0,
        "die2Auto2": 0,
        "die2Auto3": 0,
        "die2Auto4": 0,
        "die2Auto5": 0
      },
      "superLuckyRollAvailableAt": 1781307213010,
      "currentEventId": "eventLuck",
      "currentEventGeneratedAt": 1781307104087,
      "currentEventData": {
        "id": "eventLuck",
        "label": "Double Luck Weekend",
        "luck": 0.5
      },
      "currentEventFetchedAt": 1781307104087,
      "manualStreak": 0,
      "lastManualRollAt": 1781307198010,
      "luckyRollAvailableAt": 1781307212226,
      "lastSessionAt": 1781307242225,
      "playtimeMs": 38217395.09999965,
      "prestigeLevel": 0,
      "prestigePoints": 0,
      "achievementsUnlocked": {
        "rare_egg": 1781176093014,
        "first_shiny": 1781176114628,
        "roll_100": 1781176117381,
        "jackpot_1": 1781176117867,
        "epic_egg": 1781176282676,
        "shiny_10": 1781176315976,
        "roll_1k": 1781176320370,
        "legendary_egg": 1781176558129,
        "roll_10k": 1781176581927,
        "coins_1m": 1781176663128,
        "gems_500": 1781176689940,
        "shiny_divine": 1781176903743,
        "void_egg": 1781299355251
      },
      "settings": {
        "darkMode": false,
        "soundEnabled": true,
        "language": "en",
        "activeTheme": "celestial",
        "unlockedThemes": [
          "classic",
          "meadow",
          "sunset",
          "celestial"
        ],
        "filters": {
          "collectionSearch": "",
          "codexSearch": "",
          "collectionRarity": "all",
          "collectionOwned": "all",
          "codexRarity": "all",
          "codexOwned": "owned",
          "codexShinyOnly": true,
          "shopSearch": "",
          "gemShopSearch": ""
        }
      },
      "daily": {
        "lastClaimAt": 1781272101002
      },
      "stats": {
        "rollsSinceLastEgg": 0,
        "rollsSinceLastRarePlus": 22,
        "jackpotsHit": 50213
      },
      "duelBuffExpiresAt": 0,
      "lastSavedAt": 1781307242225,
      "prestigeMilestonesClaimed": [
        "prestige_5"
      ],
      "prestigeMilestoneLuck": 0.02,
      "weeklyChallenges": {
        "weekId": 2945,
        "tasks": {
          "rolls_500": {
            "progress": 500,
            "claimed": true
          },
          "fusion_3": {
            "progress": 1,
            "claimed": false
          },
          "hatch_1": {
            "progress": 1,
            "claimed": true
          },
          "discover_1": {
            "progress": 1,
            "claimed": false
          },
          "streak_10": {
            "progress": 123,
            "claimed": true
          }
        }
      },
      "guildId": "guild_1781266836678_dspts7",
      "guildRole": "leader",
      "seasonRolls": 48156460
    }
  },
  "aliensrreal": {
    "password": "sjfrpone",
    "coins": 0,
    "gems": 0,
    "rolls": 0,
    "createdAt": 1781262990267,
    "save": null
  }
};
